language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - "pypy"
  - "pypy3"
install:
  - pip install -e .
  - pip install coverage
script:
  - coverage run --source=vue setup.py test
