language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.6
  - 3.7
  - 3.8
  - "pypy3"
install:
  - pip install -e .
  - pip install coverage flake8 isort
  - if [[ $TRAVIS_PYTHON_VERSION != "pypy3" ]]; then pip install black; fi
script:
  - coverage run --source=vue setup.py test
  - flake8 ./vue --ignore=E501
  - flake8 ./tests --ignore=E501
  - isort ./vue/*.py --check-only
  - isort ./tests/*.py --check-only
  - if [[ $TRAVIS_PYTHON_VERSION != "pypy3" ]]; then black ./vue --check && black ./tests --check; fi
