language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "pypy"
  - "pypy3"
install:
  - pip install -e .
  - pip install coverage flake8 isort black
script:
  - coverage run --source=vue setup.py test
  - flake8 ./vue --ignore=E501
  - flake8 ./tests --ignore=E501
  - isort ./vue/*.py --check-only
  - isort ./tests/*.py --check-only
  - black ./vue --check
  - black ./tests --check
